var prompts = [
    "<strong>{A}</strong> and <strong>{B}</strong> resting together and talking to each other before falling asleep.",
    "<strong>{B}</strong> and <strong>{A}</strong> touching their foreheads against each other, sharing kisses.",
    "<strong>{B}</strong> and <strong>{A}</strong> exploring each others' bodies, but not in a sexual way. Finding their different birthmarks, looking over each others' scars and sharing the stories behind them, running their hands over one another and just appreciating the feeling of the other person next to them.",
    "<strong>{A}</strong> and <strong>{B}</strong> go to a fair/amusement park and <strong>{A}</strong> wants to go on the roller coaster and <strong>{B}</strong> agrees. Later, <strong>{B}</strong> regrets their decision and ends up clinging onto <strong>{A}</strong> for dear life.",
    "<strong>{B}</strong> and <strong>{A}</strong> are on a ferris wheel, and everything is going great - until it gets stuck at the very top. For thirty whole minutes.",
    "<strong>{B}</strong> prevents <strong>{A}</strong> from getting out of bed by cuddling them.",
    "<strong>{A}</strong> is about to leave for work. <strong>{B}</strong> asks them if they've forgotten anything, and <strong>{A}</strong> gives them a kiss. <strong>{B}</strong> turns red and opens their hand to reveal <strong>{A}</strong>'s keys/wallet/etc., saying 'I meant this, but thanks.'",
    "<strong>{A}</strong> and <strong>{B}</strong> playing with sidewalk chalk like they're kids again.",
    "<strong>{A}</strong> and <strong>{B}</strong> huddled by the fireplace at night after spending the day in the fresh snow.",
    "<strong>{B}</strong> and <strong>{A}</strong>'s first holiday season together.",
    "<strong>{B}</strong> wants to use their laptop on the couch, but <strong>{A}</strong> always occupies the space in their lap.",
    "<strong>{A}</strong> doesn't like talking on the phone, but <strong>{B}</strong> always calls them instead of texting. <strong>{B}</strong> admits that it's because they want to hear <strong>{A}</strong>'s voice.",
    "<strong>{A}</strong> wakes to find that it had snowed overnight and gets excited about playing in it. <strong>{B}</strong> gets excited because this means that when <strong>{A}</strong> comes inside, it will be time for cuddling by the fire.",
    "<strong>{B}</strong> drags <strong>{A}</strong> into the freezing cold to make a snowman.",
    "NSFW//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> sending each other nudes.",
    "<strong>{B}</strong> and <strong>{A}</strong> adopting a pet, and arguing over potential names.",
    "<strong>{A}</strong> being careful (or not at all careful) taking off <strong>{B}</strong>'s shirt because <strong>{B}</strong> is extremely ticklish.",
    "<strong>{A}</strong> taking <strong>{B}</strong> out for Valentine's Day to cheer them up after their original plans with someone else fell through. As <strong>{A}</strong> tries their best to make <strong>{B}</strong> happy and succeeds after only a few attempts, <strong>{B}</strong> realizes they would have rather been with <strong>{A}</strong> anyways.",
    "<strong>{B}</strong> hurt their ankle and is laid up with a cast and crutches. <strong>{A}</strong> is sitting next to them, doodling little hearts on their cast to cheer them up.",
    "<strong>{B}</strong> lends their jacket to <strong>{A}</strong>. When <strong>{A}</strong> is home, they realize they still have <strong>{B}</strong>'s sweater and find <strong>{B}</strong>'s iPod. Out of curiosity, <strong>{A}</strong> looks through <strong>{B}</strong>'s music and finds a playlist titled with <strong>{A}</strong>'s name.",
    "<strong>{A}</strong> is alone in the rain because they forgot to bring an umbrella, <strong>{B}</strong> offers to share theirs.",
    "<strong>{B}</strong> telling really dumb or corny jokes to <strong>{A}</strong>, thinking they are so clever and funny. <strong>{A}</strong> just thinks <strong>{B}</strong> is adorable for thinking the jokes are funny.",
    "<strong>{A}</strong> teaching <strong>{B}</strong> how to kiss, and <strong>{B}</strong> ends up kissing <strong>{A}</strong> really quick, nervously asks 'Like that?' and leaves <strong>{A}</strong> silent and flustered for a moment.",
    "<strong>{B}</strong> absolutely loves the taste of the chap stick/lip balm <strong>{A}</strong> uses, so they keep stealing kisses from <strong>{A}</strong>.",
    "<strong>{A}</strong> and <strong>{B}</strong> falling asleep together with their heads on the other's shoulder/head in the backseat of the car while their friend is driving.",
    "<strong>{B}</strong> holding a sobbing <strong>{A}</strong>. <strong>{A}</strong> cries themselves to sleep with their face buried into <strong>{B}</strong>.",
    "<strong>{A}</strong> and <strong>{B}</strong> sleeping on top of each other (bed, couch, hammock, etc.) when <strong>{B}</strong> falls down on the floor.",
    "<strong>{A}</strong> and <strong>{B}</strong> watching a horror movie. <strong>{A}</strong> can't sleep that night and <strong>{B}</strong> comforts them in a cuddle.",
    "<strong>{B}</strong> tossing snowballs at <strong>{A}</strong>'s window, not knowing the window is open and has no screen.",
    "<strong>{B}</strong> gets the hiccups, causing <strong>{A}</strong> to laugh every time they try to talk until <strong>{A}</strong> gets the hiccups too.",
    "<strong>{B}</strong> and <strong>{A}</strong> break up, but they have a pet and neither of them want to give it up. Then they spend a few days each with the pet separately. But it kinda helps them get together again.",
    "<strong>{A}</strong> and <strong>{B}</strong> at a theme park or carnival, and walking towards one of the many games to win a large stuffed animal. <strong>{A}</strong> is sure that they can win the game, but after many attempts (and a lot of cash down the drain) <strong>{A}</strong> gives up. <strong>{B}</strong>, however, tries and succeeds on their first go.",
    "<strong>{A}</strong> and <strong>{B}</strong> unable to sleep after watching a horror movie, but neither will admit that the movie scared them.",
    "<strong>{A}</strong> trying to get something on their computer to work. While they’re getting frustrated and flipping out, <strong>{B}</strong> is sitting nearby cracking up.",
    "<strong>{B}</strong> likes stealing <strong>{A}</strong>'s phone to change <strong>{A}</strong>'s phone wallpaper into something stupid (like unattractive pictures of <strong>{A}</strong>'s face or doing something like picking their nose). <strong>{B}</strong> is doing another routine swipe of <strong>{A}</strong>'s phone, but doesn't have the heart to change it because this time because <strong>{A}</strong>'s phone wallpaper is a cute picture of the two of them (like their first date together, or the only picture they have together).",
    "<strong>{A}</strong> cuddling with a body pillow, pretending that it's <strong>{B}</strong>.",
    "<strong>{B}</strong> getting shy about being naked in front of <strong>{A}</strong> for the first time.",
    "<strong>{B}</strong> and <strong>{A}</strong> were separated for several years for reasons they couldn't help. They finally find each other and have a heartfelt reunion.",
    "<strong>{A}</strong>'s mom gives <strong>{A}</strong> and <strong>{B}</strong> very cheesy, matching shirts/sweaters/scarfs. <strong>{B}</strong> does their very best to pretend that they love it.",
    "<strong>{B}</strong> having to help <strong>{A}</strong> undress after an injury.",
    "<strong>{B}</strong> snuggling up to <strong>{A}</strong> because it's cold.",
    "<strong>{A}</strong> using <strong>{B}</strong>'s lap as a pillow.",
    "<strong>{B}</strong> buying <strong>{A}</strong> a special treat when they go out shopping.",
    "<strong>{A}</strong> giving <strong>{B}</strong> a tight hug that makes them lose their breath.",
    "<strong>{A}</strong> staying up half the night to finish a game with <strong>{B}</strong>.",
    "<strong>{B}</strong> giving <strong>{A}</strong> a back massage when they flop on the couch or bed.",
    "<strong>{B}</strong> making a goofy face until <strong>{A}</strong> notices and laughs.",
    "<strong>{B}</strong> trying their best to be quiet while <strong>{A}</strong> is taking a nap.",
    "<strong>{A}</strong> helping <strong>{B}</strong> dry and brush their hair after a shower.",
    "<strong>{B}</strong> running out in the middle of the night to get a snack that <strong>{A}</strong> is craving.",
    "<strong>{A}</strong> wrapping a blanket around <strong>{B}</strong> when they are sitting on the couch and watching a show.",
    "<strong>{B}</strong> tucking <strong>{A}</strong>'s hair behind their ear to help them get it out of their face.",
    "<strong>{A}</strong> sharing a drink with <strong>{B}</strong> from the same straw.",
    "<strong>{A}</strong> doing a chore they know <strong>{B}</strong> isn't fond of.",
    "<strong>{B}</strong> wearing clothes in <strong>{A}</strong>'s favorite color.",
    "<strong>{B}</strong> tracing their names together in the sand.",
    "<strong>{A}</strong> writing <strong>{B}</strong> name in a heart/under the love umbrella/etc. in their notebook together with their own name.",
    "<strong>{B}</strong> and <strong>{A}</strong> sharing a soft smile across a crowded room.",
    "<strong>{A}</strong> and <strong>{B}</strong> making out until they're breathless.",
    "<strong>{B}</strong> calming <strong>{A}</strong> down when they have a bad dream.",
    "<strong>{B}</strong> following <strong>{A}</strong>'s family traditions that they enjoy.",
    "<strong>{A}</strong> telling <strong>{B}</strong> a dumb joke just to see their smile.",
    "<strong>{A}</strong> participating in <strong>{B}</strong>'s hobby even if it doesn't personally interest them.",
    "<strong>{B}</strong> buying <strong>{A}</strong> something unrequested because it made <strong>{B}</strong> think of them.",
    "<strong>{B}</strong> lightly kissing <strong>{A}</strong> on top of a freshly formed bruise.",
    "<strong>{A}</strong> and <strong>{B}</strong> recreating their first kiss.",
    "<strong>{A}</strong> giving <strong>{B}</strong> a kiss before going to work and they are still in bed.",
    "Food//<br><br><br><strong>{B}</strong> making <strong>{A}</strong> their favorite meal when they are having a hard day.",
    "<strong>{B}</strong> traveling long distances just to see <strong>{A}</strong>.",
    "<strong>{B}</strong> tucking the sheets around <strong>{A}</strong> when they stir during the night.",
    "<strong>{B}</strong> holding <strong>{A}</strong>'s hands when they are shaking.",
    "<strong>{A}</strong> and <strong>{B}</strong> spending the night on the perfect hill for stargazing.",
    "<strong>{B}</strong> and <strong>{A}</strong> throwing food for the ducks at the duck pond.",
    "<strong>{A}</strong> and <strong>{B}</strong> having a picnic under a large fruit tree in the middle of summer.",
    "<strong>{A}</strong> and <strong>{B}</strong> going to explore an abandoned house on the edge of town.",
    "<strong>{B}</strong> and <strong>{A}</strong> testing beds and couches at a furniture store.",
    "<strong>{A}</strong> and <strong>{B}</strong> playing on the swings at a small playground that nobody goes to anymore.",
    "<strong>{A}</strong> and <strong>{B}</strong> lighting fall-scented candles.",
    "<strong>{B}</strong> and <strong>{A}</strong> carving pumpkins.",
    "<strong>{A}</strong> and <strong>{B}</strong> making crafts and having a playful argument over their creative differences.",
    "<strong>{A}</strong> and <strong>{B}</strong> decorating their house with seasonal decorations.",
    "<strong>{A}</strong> and <strong>{B}</strong> drowning in oversized sweaters during chilly days.",
    "<strong>{A}</strong> and <strong>{B}</strong>'s child coming to sleep with them after having a bad dream.",
    "<strong>{A}</strong> and <strong>{B}</strong> remembering their first kiss… and they have very different takes on it.",
    "<strong>{B}</strong> hiding in a closet to jump out and surprise <strong>{A}</strong>, but <strong>{A}</strong> just keeps not going near the closet by chance.",
    "<strong>{B}</strong> and <strong>{A}</strong> tossing coins in a well and making wishes.",
    "<strong>{A}</strong> and <strong>{B}</strong>  living together for the first time.",
    "<strong>{B}</strong> and <strong>{A}</strong> texting.", 
    "<strong>{A}</strong> and <strong>{B}</strong> writing letters to each other.",
    "<strong>{A}</strong> and <strong>{B}</strong> holding hands because there's a crowd but not letting go when they get out of it.",
    "<strong>{B}</strong> and <strong>{A}</strong> going swimming together.",
    "<strong>{A}</strong> and <strong>{B}</strong> shopping, with one of them being way more excited about it than the other who just kinda drags around and carries their bags.",
    "<strong>{B}</strong> sneaking into <strong>{A}</strong>'s room through their window.",
    "Food//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> cooking something without the recipe, because <strong>{B}</strong> is confident they know how to cook it from memory.",
    "<strong>{B}</strong> and <strong>{A}</strong> taking couple's quizzes on the Internet.",
    "<strong>{A}</strong> is scared of the thunder and <strong>{B}</strong> tries to calm them down during an particularly heavy storm.",
    "Food//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> sharing ice cream/cake/a dessert.",
    "<strong>{B}</strong> gets into a heated argument with someone. <strong>{B}</strong> begins threatening them, so <strong>{A}</strong>, picks up <strong>{B}</strong> and carries/drags them out of the room before anyone gets hurt.",
    "<strong>{B}</strong> and <strong>{A}</strong> getting locked in a store after closing.",
    "<strong>{B}</strong> getting up in the middle of the night to make a snack and accidentally waking up <strong>{A}</strong> because they didn't stop the microwave's obnoxious beeping in time.",
    "<strong>{B}</strong> and <strong>{A}</strong> are drawing each other. <strong>{A}</strong> makes a spectacular drawing and <strong>{B}</strong>'s drawing does turn out to be that good. However, <strong>{A}</strong> keeps <strong>{B}</strong>'s drawing and treasures it.",
    "<strong>{A}</strong> having to comfort <strong>{B}</strong> because <strong>{B}</strong> just encountered a very large, unpleasant bug outside that scared them.",
    "<strong>{B}</strong> and <strong>{A}</strong> go on a camping trip. <strong>{B}</strong> forgets to bring a sleeping bag, so they have to squeeze into <strong>{A}</strong>'s sleeping bag with them.",
    "<strong>{B}</strong> catches a cold so <strong>{A}</strong> makes them breakfast in bed.",
    "<strong>{A}</strong> falling asleep in <strong>{B}</strong>'s lap. <strong>{B}</strong> holds <strong>{A}</strong> close and doesn't move from their spot for hours.",
    "<strong>{B}</strong> giving <strong>{A}</strong> a piggyback ride.",
    "<strong>{A}</strong> and <strong>{B}</strong> going to a drive-thru fast food place. When they get home, it is discovered that the staff did not prepare <strong>{A}</strong>'s order properly. Despite <strong>{A}</strong> insisting they don't mind, <strong>{B}</strong> drives back to the fast food place to demand a new meal be made for <strong>{A}</strong>.",
    "<strong>{B}</strong> screaming over a picture of <strong>{A}</strong> from long before they met. <strong>{B}</strong> describes the younger <strong>{A}</strong> as a tiny precious child, then looks at <strong>{A}</strong>, and says 'Well, you're still a tiny precious child'.",
    "<strong>{B}</strong> holding <strong>{A}</strong> very close, close enough to smell their hair. They whisper into <strong>{A}</strong>'s ear: 'I don't like your new shampoo'",
    "A friend drawing on <strong>{A}</strong> and <strong>{B}</strong>'s faces when they sleep. They wake up to see each other faces covered in silly doodles.",
    "<strong>{A}</strong> hogs all the blankets and <strong>{B}</strong> gets cold so they cling tightly to <strong>{A}</strong> for warmth.",
    "<strong>{A}</strong> coming home from a cuddly date with <strong>{B}</strong> and realizing that their shirt smells like <strong>{B}</strong>. <strong>{A}</strong> pulls their shirt up to their face to smell it before it fades away.",
    "<strong>{B}</strong> falls asleep in <strong>{A}</strong>'s lap and <strong>{A}</strong> has a conversation with someone else while stroking <strong>{B}</strong>'s hair as if they were a sleeping cat.",
    "<strong>{B}</strong> reading in bed while <strong>{A}</strong> rests their head on <strong>{B}</strong>'s shoulder, sleeping.",
    "<strong>{A}</strong> goes over to <strong>{B}</strong>'s home after staying up all night. Even though they do their best to stay awake, they end up falling asleep while cuddling <strong>{B}</strong>. <strong>{A}</strong> is quite embarrassed (and half-asleep) when they wake up, but <strong>{B}</strong> doesn't mind.",
    "<strong>{A}</strong>: Ah shit <br><strong>{B}</strong>: Watch your fucking language",
    "<strong>{B}</strong> and <strong>{A}</strong> carrying around balloons so they don't get lost in the crowd.",
    "AU//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> as the main characters in the last show you watched/book you read/game you played.",
    "<strong>{B}</strong> spending all their money on <strong>{A}</strong>, who scolds them for it.",
    "<strong>{A}</strong> and <strong>{B}</strong> playing a co-op video game and <strong>{A}</strong> keeps dicking around and <strong>{B}</strong> just wants to get past the first level god dammit.",
    "<strong>{B}</strong> staring admiringly at <strong>{A}</strong> from across the room. A friend whispers into <strong>{B}</strong>'s ear: 'Why are you so thirsty?'",
    "<strong>{A}</strong> touching <strong>{B}</strong>'s face and telling them that their face is really soft.",
    "<strong>{B}</strong> and <strong>{A}</strong> are about to kiss when instead they accidentally hit foreheads really hard and have matching bruises.",
    "<strong>{B}</strong> telling <strong>{A}</strong> a story but <strong>{A}</strong> isn't paying attention at all because they're too busy thinking about what a cutie <strong>{B}</strong> is.",
    "AU//<br><br><br><strong>{A}</strong> is the barista at a coffee shop and always screws up <strong>{B}</strong>'s name on purpose.",
    "<strong>{B}</strong> and <strong>{A}</strong> getting sick at the same time.",
    "<strong>{B}</strong> sings extremely well but has a lot of difficulty playing musical instruments and <strong>{A}</strong> can play their musical instrument very well but their singing voice is terrible.",
    "<strong>{B}</strong> and <strong>{A}</strong> haven't kissed yet. Each time <strong>{B}</strong> sees <strong>{A}</strong> they think to themselves 'I've gotta do it this time' but they keep being too shy to do anything. One day a friend asks <strong>{B}</strong> if <strong>{A}</strong> has ever tried to kiss them and <strong>{B}</strong> just screams.",
    "<strong>{B}</strong> pressing their forehead against <strong>{A}</strong>'s forehead to check if they have a fever.",
    "<strong>{B}</strong> reminiscing about the time they first met <strong>{A}</strong>. They're still in awe of how far they've come.",
    "<strong>{A}</strong> making <strong>{B}</strong> some hot chocolate.",
    "<strong>{B}</strong> and <strong>{A}</strong> having a snowball fight.",
    "<strong>{A}</strong> and <strong>{B}</strong> spending their New Year's Eve on a party with their friends and sharing their New Year's kiss in front of everyone.",
    "<strong>{B}</strong> and <strong>{A}</strong> walking through town, holding hands while it snows.",
    "<strong>{A}</strong> and <strong>{B}</strong> trying to hide their relationship. However, it turns out everyone knows they're dating.",
    "<strong>{B}</strong> and <strong>{A}</strong> battling against each other. Whether it's serious or playful is up to you...",
    "<strong>{B}</strong> and <strong>{A}</strong> being brought together by their mutual love for a third party, only to slowly develop feelings for each other over time.",
    "NSFW//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> enjoying a night of stargazing. Things are going well and they start to kiss/make out when a storm hits. Instead of seeking shelter from the rain, they make love under the night sky, not caring if they're drenched, just caught up in the moment of passion itself.",
    "NSFW//<br><br><br><strong>{B}</strong> and <strong>{A}</strong> staying at a hotel outside of town for a lazy, romantic weekend, most of which they spend nude. <strong>{B}</strong> decides that they feel too comfortable and doesn't want to get up to go out for food, so <strong>{A}</strong> decides to order out for them and get dressed just enough to meet the delivery person at the door. While <strong>{A}</strong> is accepting the order, <strong>{B}</strong> wraps up in a sheet and comes up behind them, smug as both <strong>{A}</strong> and the delivery person become flustered.",
    "<strong>{B}</strong> kissing away <strong>{A}</strong>'s tears.",
    "<strong>{B}</strong> showing <strong>{A}</strong> some of their favorite vines and memes.",
    "<strong>{B}</strong> has worked up the courage to propose to <strong>{A}</strong>.  day they go to propose, though, <strong>{A}</strong> gets on one knee, and holds out a ring.",
    "AU//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> meet in university at one of the neighboring restaurants when they both realize they’re skipping the same class.",
    "AU//<br><br><br>They are high school students. <strong>{B}</strong> gets detention. <strong>{A}</strong>, not wanting to be alone, joins them.",
    "<strong>{A}</strong> and <strong>{B}</strong> in high school, staying up all night together to study for a big test the next day.",
    "<strong>{A}</strong> and <strong>{B}</strong> going to Build-A-Bear.",
    "<strong>{A}</strong> and <strong>{B}</strong> going on social media and finding all of your posts about them.",
    "AU//<br><br><br><strong>{B}</strong> and <strong>{A}</strong> met when they moved into the same town in the Animal Crossing universe. (What species each of them are is totally up to you.)",
    "<strong>{B}</strong> is trying to impress <strong>{A}</strong> and ends up falling flat on their face. As <strong>{B}</strong> lays on the ground and slowly die from embarrassment, <strong>{A}</strong> has a mind blowing realization that they actually really like <strong>{B}</strong> and when they help <strong>{B}</strong> up off the ground, they pull them into a kiss.",
    "<strong>{A}</strong> is chewing the last piece of gum in a really good pack so <strong>{B}</strong> pulls them into a kiss to lowkey steal it out of <strong>{A}</strong>'s mouth",
    "<strong>{B}</strong> and <strong>{A}</strong> hosting a holiday open-mic night and performing 'Baby It's Cold Outside' together",
    "AU//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> are neighbors and they don't necessarily like/notice each other at first, but <strong>{B}</strong> gets kittens and <strong>{A}</strong> comes over just to spend some time with them and it charms <strong>{B}</strong>'s heart.",
    "<strong>{B}</strong> gets locked out of their house while their family is gone, so they spend the night at <strong>{A}</strong>'s place.",
    "Before they started dating, <strong>{A}</strong> and <strong>{B}</strong> are best friends. Like the best friends that have known each other since they were in diapers. Whenever <strong>{A}</strong> would get upset, hurt or just really tired, they would snuggle up on <strong>{B}</strong> and nuzzle their face into the crook of <strong>{B}</strong>’s neck. It’s completely platonic, nothing romantic about it whatsoever. <br>When <strong>{A}</strong> and <strong>{B}</strong> finally confess their feelings for one another and begin dating, <strong>{A}</strong> immediately snuggles up in 'their' spot on <strong>{B}</strong> and just completely relaxes. <strong>{B}</strong> asks why they always do this, and <strong>{A}</strong> replies that it makes them feel safe and calm.",
    "<strong>{A}</strong> can't sleep without <strong>{B}</strong> by their side.",
    "<strong>{B}</strong> and <strong>{A}</strong> going on a nice walk in the woods when it suddenly starts to downpour.",
    "<strong>{A}</strong> and <strong>{B}</strong> slow dancing with no music, arms wrapped tightly around each other, breath mingling.",
    "<strong>{B}</strong> and <strong>{A}</strong> sharing soft kisses, lips barely touching, just chaste little things that leave both parties irrationally breathless.",
    "<strong>{B}</strong> helping <strong>{A}</strong> with simple tasks, like brushing their hair, or putting on jewelry, where it’s obviously an excuse to be close to each other, but neither are complaining.",
    "<strong>{A}</strong> and <strong>{B}</strong> pressing their faces together sleepily, not even kissing, just resting their foreheads together, noses brushing, breathing each other in.",
    "<strong>{B}</strong> smiling shyly, cheeks tinging pink, because they were caught staring at <strong>{A}</strong>.",
    "<strong>{A}</strong> and <strong>{B}</strong> playing joyous and silly music to dance around the living room to.",
    "<strong>{B}</strong> and <strong>{A}</strong> going out for coffee one morning and <strong>{A}</strong> already knows <strong>{B}</strong>'s order by heart.",
    "<strong>{B}</strong> kissing <strong>{A}</strong> under the rain without an umbrella after a silly argument, proceeding to giggle it out.",
    "<strong>{A}</strong> has been planning to propose for a while, they've bought the ring and everything. One day, they somehow lose the ring only for <strong>{B}</strong> to unexpectedly find it. Bonus: <strong>{B}</strong> questions a flustered <strong>{A}</strong> about the ring. Bonus 2: <strong>{B}</strong> uses the ring to propose instead.",
    "<strong>{B}</strong> looks at <strong>{A}</strong> and gently cups their face to examine it. <strong>{A}</strong> is a little confused and asks what's <strong>{B}</strong> doing. 'Hold on, there's something on your face,' <strong>{B}</strong> responds and then kisses <strong>{A}</strong>. 'It was me.' <br><strong>{A}</strong> becomes red and flustered.",
    "<strong>{B}</strong> returning the engagement ring they got for <strong>{A}</strong> to the jeweller. Not because <strong>{A}</strong> said no, but because <strong>{A}</strong> had worked up the courage to propose before <strong>{B}</strong> did.",
    "<strong>{A}</strong> and <strong>{B}</strong> go separately to a New Year’s Party, and end up standing next to each other during the countdown to midnight.",
    "<strong>{B}</strong>  makes a New Year’s Resolution – but <strong>{A}</strong> makes it difficult for them to keep it.",
    "<strong>{B}</strong> gets confetti in their hair. <strong>{A}</strong> notices.",
    "<strong>{A}</strong> loves to dance at parties - <strong>{B}</strong> not so much.",
    "Someone 'accidentally' left the Christmas misteltoe up at a New Year’s Eve party attended by both <strong>{B}</strong> and <strong>{A}</strong>.",
    "On New Year's Eve, <strong>{A}</strong> and <strong>{B}</strong> reflect on their entire year together.",
    "<strong>{B}</strong> has never seen <strong>{A}</strong> in a tuxedo/ball gown before.",
    "<strong>{A}</strong> makes an unexpected toast in honor of <strong>{B}</strong>.",
    "<strong>{A}</strong> and <strong>{B}</strong> in the morning after a one night stand.",
    "<strong>{A}</strong> and <strong>{B}</strong> are in an established long distance relationship, <strong>{A}</strong> surprises <strong>{B}</strong> by showing up right before midnight on New Year's Eve.",  
    "Food//<br><br><br><strong>{A}</strong> comes back home to see the mess <strong>{B}</strong> made in the kitchen trying to cook for them.",
    "<strong>{B}</strong> heroically saving <strong>{A}</strong> from a spider by picking it with a glass and throwing it outside.",
    "<strong>{A}</strong> and <strong>{B}</strong> hanging out in a garden/field of wildflowers and making flower crowns for each other.",
    "<strong>{A}</strong> trying their hardest to prank <strong>{B}</strong>, but they fail each and every single time.",
    "<strong>{B}</strong> keeps asking weird/strange existential (or otherwise way too deep for 1am) questions and <strong>{A}</strong> only wants to go to sleeep.",
    "<strong>{A}</strong> and <strong>{B}</strong> having water baloon/water gun fight.",
    "<strong>{B}</strong> finding this prompt generator and putting up their name together with <strong>{A}</strong>'s name and reacting to the prompts they get.",
    "<strong>{A}</strong> and <strong>{B}</strong> singing a duet together.",
    "<strong>{A}</strong> comes out as trans. <strong>{B}</strong> does their best to support them.",
    "<strong>{B}</strong> and <strong>{A}</strong> tell each other how they miss one another.",
    "<strong>{A}</strong> and <strong>{B}</strong> getting married.",
    "<strong>{A}</strong> and <strong>{B}</strong> making crafts that remind them of one another.",
    "<strong>{B}</strong> and <strong>{A}</strong> started out hating each other but slowly started developing feelings for one another.",
    "<strong>{B}</strong> wakes <strong>{A}</strong> at 4 am because they wants someone to eat cereal with. <strong>{A}</strong> questions why, but <strong>{B}</strong> surprises them and says 'I just wanted a reason to be with you, is all...'",
    "<br> <strong>{A}</strong>: It's going to be Christmas soon, <strong>{B}</strong>. <br> <strong>{B}</strong>: So what, <strong>{A}</strong>.",
    "<strong>{A}</strong>: First of all you just ignored my cats dressed up as Santa, so fuck you. Secondly, <br>[<strong>{A}</strong> is typing...]",
    "<strong>{A}</strong> and <strong>{B}</strong> going star gazing at the observatory.",
    "<strong>{B}</strong> and <strong>{A}</strong> staying home and ordering take out bc it’s too hot outside.",
    "<strong>{B}</strong> and <strong>{A}</strong> staying in a small town and exploring the little shops and cute restaurants.",
    "<strong>{A}</strong> and <strong>{B}</strong> camping beside a lake and going swimming as the sun sets.",
    "<strong>{B}</strong> and <strong>{A}</strong> roasting marshmallows on a fire.",
    "<strong>{A}</strong> and <strong>{B}</strong> cuddling under the stars.",
    "<strong>{B}</strong>:*Kisses <strong>{A}</strong>'s forehead*<br><strong>{A}</strong>:*frowns* You missed<br><strong>{B}</strong>:...?<br><strong>{A}</strong>:*Leans forward and kisses <strong>{B}</strong>'s lips*",
    "<strong>{A}</strong>: Goodbye.",
    "<strong>{B}</strong>: I always knew it would end like this.",
    "<strong>{B}</strong>: I don’t want to be alone right now.",
    "<strong>{B}</strong>: I’ve got you now.",
    "<strong>{B}</strong>: I love you <br> <strong>{A}</strong>: *shoving laundry basket into <strong>{B}</strong>'s hands* stop saying I love you to get out of chores",
    "<strong>{A}</strong> and <strong>{B}</strong> going camping",
    "<strong>{B}</strong> and <strong>{A}</strong> on a shopping date",
    "<strong>{A}</strong>: Don’t worry, I’ve been arrested before. I’ll get us out of this.",
    "<strong>{A}</strong>: I love you. <br> <strong>{B}</strong>: Pathetic.",
    "<strong>{B}</strong>: I know that I hurt you. I know that nothing I can say will change the past. But…I’m hoping that you’ll forgive me in the end. I’m hoping that I can make this right.",
    "<strong>{B}</strong>: Do you hate me or something? <br><strong>{A}</strong>: Not at all. I’m actually quite in love with you, really.",
    "<strong>{A}</strong> and <strong>{B}</strong> are pretending to be married because they want a discount on a vacation special to an expensive resort. What happens? Do they get found out?",
    "<strong>{A}</strong> and <strong>{B}</strong> go to school together. <strong>{A}</strong> got <strong>{B}</strong> a huge ass teddy bear for a special occassion and <strong>{B}</strong> is mad cause they have to carry it around all day.",
    "<strong>{A}</strong> and <strong>{B}</strong> decide to do a partner costume! Who or what would they dress up as?",
    "<strong>{B}</strong> and <strong>{A}</strong> getting matching tattoos",
    "<strong>{A}</strong> and <strong>{B}</strong> falling asleep under the stars together... Only to wake up covered in bug bites.",
    "<strong>{B}</strong> and <strong>{A}</strong> sleeping together for the first time.  No sex, just sleeping.  When <strong>{B}</strong> wakes up, they see <strong>{A}</strong> still asleep. <strong>{B}</strong> smiles and wakes them up with a sweet kiss. <strong>{A}</strong>, once aware of what’s happening, kisses back.",
    "<strong>{A}</strong> and <strong>{B}</strong> are lost in the woods together.",
    "Imagine the big, bright smile on <strong>{B}</strong>'s face when <strong>{A}</strong> finally says ‘I love you’ for the first time.",
    "<strong>{A}</strong> runs across the road to pet <strong>{B}</strong>'s pet.",
    "<strong>{B}</strong> is playing a video game even though they’re really tired. They end up falling asleep during the game. <strong>{A}</strong> walks up and sees <strong>{B}</strong> sleeping peacefully, and falling out of their hands, a controller/handheld. Instead of waking up <strong>{B}</strong> or turning off the game, <strong>{A}</strong> picks up the controller/handheld and begins to play.",
    "<strong>{A}</strong> gets addicted to painting nails and forces <strong>{B}</strong> to let their nails get painted on.",
    "<strong>{B}</strong> and <strong>{A}</strong> have to work with each other on a psychology project. A psychology project on attraction.",
    "Imagine <strong>{A}</strong> wants to spice up their and <strong>{B}</strong>'s romance life and tries all sorts of cheesy tactics such as candlelit dinners, bringing fruit and whipped cream into the bedroom, sexy underwear... whether they fail or not in their romancing is another question...",
    "NSFW//<br><br><br><strong>{A}</strong> comes home to find <strong>{B}</strong> sleeping on top of the covers... completely naked.",
    "<strong>{A}</strong> and <strong>{B}</strong> getting dressed in the morning, <strong>{B}</strong> however is feeling a bit playful and decides to hold a piece of <strong>{A}</strong>'s clothing hostage so <strong>{A}</strong> has to try and get it back",
    "<strong>{B}</strong> and <strong>{A}</strong> as friends in school before they’re together. They awkwardly use each other to learn how to/practice kissing and end up making out passionately until their mouths are sore.",
    "NSFW//<br><br><br><strong>{B}</strong> handing <strong>{A}</strong> a bowl of cream/chocolate/honey and telling them to spread them on their own body where they want it licked off by <strong>{B}</strong>. <strong>{A}</strong> eagerly complies, and everything starts (or ends) with a sloppy smear on <strong>{A}</strong>'s lips.",
    "NSFW//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> both buy lingerie and try to surprise one another with it on the same night.",
    "<strong>{A}</strong> dressed up as a sexy cop for Halloween and <strong>{B}</strong> keeps surrendering to <strong>{A}</strong> by saying 'I've been very bad, you should arrest me.'",
    "<strong>{A}</strong>: You  don’t  have  to  hide  your  tears  from  me, <strong>{B}</strong>. It's okay.",
    "<strong>{B}</strong> waking <strong>{A}</strong> up with gentle kisses.",
    "<strong>{A}</strong> spontaneously kissing <strong>{B}</strong>.",
    "<strong>{B}</strong> holding <strong>{A}</strong> close.",
    "<strong>{B}</strong> gesturing at <strong>{A}</strong> to come closer.",
    "<strong>{A}</strong> grabbing <strong>{B}</strong>'s arm or hiding behind <strong>{B}</strong> because something scared them.",
    "<strong>{A}</strong> touching <strong>{B}</strong> as a show of affection/reassurance.",
    "<strong>{B}</strong> showing up at <strong>{A}</strong>'s house without explanation.",
    "<strong>{A}</strong> treating <strong>{B}</strong>'s injury.",
    "<strong>{B}</strong> getting hurt protecting <strong>{A}</strong>.",
    "<strong>{B}</strong> tickling <strong>{A}</strong>.",
    "<strong>{A}</strong> massaging <strong>{B}</strong>'s shoulders.",
    "<strong>{B}</strong> kissing <strong>{A}</strong>'s neck.",
    "<strong>{B}</strong> and <strong>{A}</strong> sharing a bath.",
    "<strong>{A}</strong> and <strong>{B}</strong> in the shower together, purely enjoying the company of each other.",
    "<strong>{B}</strong> putting flowers in <strong>{A}</strong>'s hair.",
    "<strong>{A}</strong>: You look tense, lie down and I’ll give you a massage.", 
    "<strong>{A}</strong>: Your nose gets so pink during winter...I have to kiss it.",
    "<strong>{B}</strong>: Sorry, I didn’t know you were awake, you just looked so cute and I wanted to kiss you.",
    "<strong>{B}</strong>: I like tracing the lines in your palm, it’s...distracting.",
    "<strong>{B}</strong>: It’s just so easy to pick you up!",
    "<strong>{A}</strong>: Do you want to join me in my blanket fort?",  
    "<strong>{B}</strong>: ...so that’s where all the pillows went. Mind if I lay with you?",
    "<strong>{A}</strong>: Your skin is so soft...",
    "<strong>{A}</strong>: My shirt is way too big on you...but it’s cute.",
    "<strong>{A}</strong>: I don’t know how we keep ending up in each other’s beds...",
    "<strong>{A}</strong>: You know, I really like your eyes, <strong>{B}</strong>.",
    "<strong>{A}</strong> and <strong>{B}</strong> going for an incredibly late night walk.",
    "<strong>{B}</strong> puts <strong>{A}</strong>'s favorite movie on for a movie night.",
    "Food//<br><br><br><strong>{A}</strong> offers <strong>{B}</strong> their favorite snack/drink/etc.",
    "<strong>{B}</strong> gently drapes a blanket over <strong>{A}</strong> and kisses their forehead while they’re half-asleep.",
    "<strong>{A}</strong> runs <strong>{B}</strong> a relaxing bath after a long and difficult day.",
    "<strong>{B}</strong> is experiencing a moment of great joy – only for <strong>{A}</strong> to suddenly arrive with devastating news.",
    "<strong>{B}</strong> has become bitter and, well, rather prickly, and <strong>{A}</strong> is trying to find out why they are acting so out-of-character so suddenly.",
    "<strong>{B}</strong> is suffering in the summer heat, and <strong>{A}</strong> is left desperately trying to cool them down.",
    "<strong>{A}</strong> has to face their worst fear, and <strong>{B}</strong> must help them through the experience.",
    "<strong>{A}</strong> is feeling terrible self-doubt, and <strong>{B}</strong> must try to encourage them.",
    "<strong>{A}</strong> brushes something off of <strong>{B}</strong>'s face (eyelash, food crumb, etc.)",
    "<strong>{B}</strong> shares a drink or a snack with <strong>{A}</strong>.",
    "<strong>{A}</strong> helps <strong>{B}</strong> shave.",
    "<strong>{A}</strong> applying make up on <strong>{B}</strong>.",
    "<strong>{B}</strong> helping <strong>{A}</strong> wash up (whether it be their hair, body, some blood off their hands, etc.)",
    "<strong>{B}</strong> giving <strong>{A}</strong> a smile after making eye contact.",
    "<strong>{A}</strong> offering <strong>{B}</strong> a hand to help them with a step.",
    "NSFW//<br><br><br><strong>{B}</strong> leaning close to whisper something dirty <strong>{A}</strong>.",
    "<strong>{B}</strong> brushes a thumb over <strong>{A}</strong>'s cheek.",
    "<strong>{A}</strong> and <strong>{B}</strong> slow dance together.",
    "<strong>{B}</strong> offers <strong>{A}</strong> a place to stay.",
    "<strong>{A}</strong> gently kisses <strong>{B}</strong> on the nose.",
    "<strong>{B}</strong> gets a call from <strong>{A}</strong> in the middle of the night.",
    "<strong>{B}</strong> and <strong>{A}</strong> celebrate something together.",
    "<strong>{B}</strong> interlaces their fingers with <strong>{A}</strong>.",
    "<strong>{A}</strong> picks a flower for <strong>{B}</strong>.",
    "<strong>{B}</strong> makes <strong>{A}</strong> a hot beverage on a cold day.",
    "<strong>{A}</strong> is feeling out of it and need constant attention from <strong>{B}</strong>.",
    "<strong>{B}</strong> collapsing into <strong>{A}</strong>'s waiting arms.",
    "<strong>{A}</strong> picking <strong>{B}</strong> up.",
    "<strong>{A}</strong> calling <strong>{B}</strong> soft things like baby, sweetheart or honey.",
    "<strong>{A}</strong> waking up in the middle of the night to find <strong>{B}</strong> still working. <strong>{A}</strong> has to drag <strong>{B}</strong> back to bed.",
    "<strong>{B}</strong> waking up in the middle of the night to find that <strong>{A}</strong> isn't in their bed.",
    "<strong>{B}</strong> mumbling <strong>{A}</strong>'s name and reaching out for them.",
    "<strong>{A}</strong> has a fever. <strong>{B}</strong> takes care of them and lovingly runs their fingers through <strong>{A}</strong>'s sweaty hair.",
    "<strong>{A}</strong> says something to <strong>{B}</strong> that strikes a nerve.",
    "<strong>{A}</strong> witnesses <strong>{B}</strong> having a panic attack, flashback, or hallucination.",
    "<strong>{B}</strong> accidentally discovers a secret about <strong>{A}</strong>.",
    "<strong>{A}</strong> and <strong>{B}</strong> have a good, hard cry together.",
    "<strong>{A}</strong> comes home to find <strong>{B}</strong> snooping through their things.",
    "<strong>{A}</strong> tries convincing <strong>{B}</strong> to run away with them to an undisclosed location.",
    "<strong>{A}</strong>: There isn’t a word in the dictionary that can explain your type of beauty.",
    "<strong>{B}</strong>: Can you send me a picture? I want to prove to all of my friends that angels really do exist.",
    "<strong>{B}</strong>: Of all the stars in the sky, there are none as beautiful as you.",

    "<strong>{A}</strong>: To be honest, I just wanted a chance to look at the stars with you.",
    "<strong>{B}</strong>: I’m a child of God, I don’t do that shit.",
    "Food//<br><br><br><strong>{A}</strong> is a great cook, but <strong>{B}</strong> rarely cooks. To surprise them, <strong>{B}</strong> tries to make them something. Emphasis on tries.",
    "Food//<br><br><br><strong>{B}</strong> teaching <strong>{A}</strong> how to cook.",
    "Food//<br><br><br>It's <strong>{B}</strong>'s birthday and they have a nice, lazy, sleepy lie-in. <strong>{A}</strong> decides to cook <strong>{B}</strong> breakfast in bed and cooks all of <strong>{B}</strong>'s favourite food. <strong>{B}</strong> is delighted and showers <strong>{A}</strong> with kisses.",
    "Food//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> deciding to watch a movie together. They decide to cook up some popcorn to share, but end up arguing over how their popcorn should be prepared. <strong>{B}</strong> likes unsalted, buttered popcorn, but <strong>{A}</strong> likes theirs salty and butter-free. They spend more time arguing over how to eat their popcorn than they do watching their movie (or even deciding on a movie). Is there any hope they can solve their situation?",
    "Food//<br><br><br><strong>{A}</strong> is the cook of the family. <strong>{B}</strong> can not cook but wants to give <strong>{A}</strong> a break. Whether or not they succeed is up to you.",
    "<strong>{B}</strong> and <strong>{A}</strong> talking about their feelings in a healthy and positive space, without judgement, learning more about each other and deepening the bonds of trust that bind them together.",
    "<strong>{A}</strong> and <strong>{B}</strong> are married, and offer to babysit their friends' kid, not realizing how much of a challenge it would be.",
    "<strong>{A}</strong> and <strong>{B}</strong> decorating a Christmas tree together.",
    "<strong>{A}</strong> and <strong>{B}</strong> attending a pride parade.",
    "<strong>{B}</strong> asleep and accidentally moaning <strong>{A}</strong>'s name while they're still awake beside <strong>{B}</strong>.",
    "<strong>{B}</strong> and <strong>{A}</strong> playing games in the small arcade in their neighborhood.",
    "<strong>{A}</strong> and <strong>{B}</strong> getting a little too drunk at a New Year's Eve party.",
    "<strong>{A}</strong> running their fingers through <strong>{B}</strong>'s hair while sitting next to them on the couch.",
    "<strong>{A}</strong> letting <strong>{B}</strong> warm their cold hands under their shirt.",
    "<strong>{B}</strong> and <strong>{A}</strong> play Twister. Do things get embarrassing? Do things get steamy?",
    "<strong>{A}</strong> and <strong>{B}</strong> at a late-night gathering after everyone else has gone home, dancing in the moonlight.",
    "<strong>{A}</strong> and <strong>{B}</strong> spending the night together. <strong>{A}</strong> wakes up first in the morning and contemplates waking <strong>{B}</strong> with a kiss.<strong>{A}</strong> leans in only to hesitate centimeters away out of embarrassment. <strong>{B}</strong> opens their eyes and says, 'Well if you won't do it, I will.'",
    "<strong>{B}</strong> burns their lip on something hot, <strong>{A}</strong> kisses it better.",
    "NSFW//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> sending each other nudes.",
    "<strong>{B}</strong> and <strong>{A}</strong> accidentally dozing off in a hammock together as the sun sets and the air cools down.",
    "NSFW//<br><br><br><strong>{B}</strong> moving their hand increasingly farther up <strong>{A}</strong>/s inner thigh while <strong>{A}</strong> is driving.",
    "NSFW//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> own a store together and on a particularly slow day, <strong>{B}</strong> finds themself pinned up against a wall in the stockroom by <strong>{A}</strong>.",
    "NSFW//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> showering together for the first time, having pure intentions that are eventually forgotten, leading to steamy shower sex.",
    "NSFW//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> have a long night of incredible, hot sex. It gets intense, and a little rougher than usual. The next morning, <strong>{A}</strong> wakes up holding <strong>{B}</strong> and notices bites and bruises they left all over their body. <strong>{B}</strong> wakes up and is a little sore and achy but very satisfied and happy with the night before. <strong>{A}</strong> is having guilt over the visible marks and <strong>{B}</strong> has to reassure them that it’s okay (and maybe even that they enjoyed it).",
    "NSFW//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> playing a game unknown to the people around them, in which <strong>{A}</strong> gradually moves their hand up <strong>{B}</strong>’s leg. The game is to see how far up <strong>{A}</strong> will let <strong>{B}</strong>’s hand get between their thighs before they chicken out and stop them.",
    "<strong>{A}</strong> and <strong>{B}</strong> making out so vigorously and passionately that when they’re eventually done, it looks as though they had both just stepped out of the shower.",
    "NSFW//<br><br><br><strong>{B}</strong> buying sexy lingerie and having a boudoir photoshoot for <strong>{A}</strong>.",
    "NSFW//<br><br><br>It's summer and <strong>{B}</strong> decides to wear sundresses (and nothing else) so they can ride <strong>{A}</strong> anytime.",
    "NSFW//<br><br><br>Imagine <strong>{A}</strong> fucking <strong>{B}</strong> so good that <strong>{B}</strong> can't even get a full word out, only moans and half-uttered curses.",
    "NSFW//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> participating in No Nut November, but each of them are purposely making it very difficult for the other to succeed.",
    "NSFW//<br><br><br><strong>{A}</strong> giving <strong>{B}</strong> VERY visible hickeys.",
    "NSFW//<br><br><br>Imagine<strong>{A}</strong> and <strong>{B}</strong> being new to dating and decide to take it one step farther in the bedroom. Due to them being so inexperienced, there is a lot of shyness, giggling, and blushing when it comes to sex.",
    "NSFW//<br><br><br><strong>{A}</strong> fucking <strong>{B}</strong>'s mouth.",
    "NSFW//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> own a store together and are making out on the counter on a particularly slow day when a customer comes in. <strong>{A}</strong> stands to help the customer while <strong>{B}</strong> hides under the counter. <strong>{A}</strong> has to retain their composure while <strong>{B}</strong> starts to go down on them passionately.",
    "NSFW//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> both had a very long, frustrating day. When the two of them are home and alone together, they decide to fuck out their frustration, which ends with them both being calmer than they were before.",
    "NSFW//<br><br><br><strong>{B}</strong> handcuffs <strong>{A}</strong> to their bed and rides them whilst only wearing <strong>{A}</strong>'s shirt.",
    "NSFW//<br><br><br>strong>{A}</strong> talking to someone on the phone, when <strong>{B}</strong> strips naked and sits on their lap, kissing their neck to distract/fluster them.",
    "NSFW//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> watching a movie when a sex scene comes on. <strong>{A}</strong> looks over at <strong>{B}</strong>, who is resting on their shoulder. <strong>{A}</strong>pauses the movie as <strong>{B}</strong> finds themself being kissed passionately by <strong>{A}</strong> and they have sex on the couch.",
    "NSFW//<br><br><br><strong>{A}</strong> and <strong>{B}</strong> decide to exchange two sets of gifts for their holiday of choice; one suitable for public consumption, one not (be it lingerie, toys, etc). <strong>{A}</strong> however, mixes up which package iw which after wrapping, and puts the wrong one under the tree for the family opening of presents.",
    "NSFW//<br><br><br>Imagine <strong>{A}</strong>, the one who usually enjoys slow and romantic sex, begging <strong>{B}</strong> to fuck them so hard that they forget their name.",
]

  function clear1() {

document.getElementById("person1").value = "";
document.getElementById("person1").style.fontStyle = "normal";
}

function clear2() {

document.getElementById("person2").value = "";
document.getElementById("person2").style.fontStyle = "normal";
}


var A, B;
var str; 

function fluff() {

// Get names of OTP
A = document.getElementById("person1").value;
B = document.getElementById("person2").value;

// Get random prompt
var R1 = Math.floor(Math.random() * prompts.length);
str = prompts[R1] 

// Replace {A} & {B} in prompt with OTP names
var result = str.replace(/{A}/g, A).replace(/{B}/g, B);
document.getElementById("premise").innerHTML = result;
}

function swapname() { 
//Swapping OTP names     
var temp = A;
A = B;
B = temp;

var result = str.replace(/{A}/g, A).replace(/{B}/g, B); 
document.getElementById("premise").innerHTML = result; 
}c
